Repository knative-extensions/reconciler-test, pull requests merged in 2020-11, with the labels that each got.

#35 Use ko:// to signal that we would like the test framework to produce images.
  pkg/environment/images.go
  pkg/environment/interfaces.go
  pkg/environment/magic.go
  pkg/k8s/wait.go
  pkg/manifest/installer.go
  pkg/manifest/templates.go
  test/example/config/echo/echo.go
  test/example/config/echo/echo.yaml
  test/example/config/producer/producer.go
  test/example/config/producer/producer.yaml
  test/example/config/recorder/recorder.go
  test/example/config/recorder/recorder.yaml
Labels: approved, cla: yes, lgtm, size/L

#38 Document Reconciler Test Framework
  .github/workflows/kind-e2e.yaml
  README.md
  pkg/environment/flags.go
  pkg/feature/feature.go
  pkg/test_images/eventshub/sender/sender.go
  test/config/100-namespace.yaml
  test/config/200-config-logging.yaml
  test/config/200-config-tracing.yaml
  test/example/echo_feature.go
  test/example/examples_test.go
  test/example/ko_publish_test.go
  test/example/main_test.go
  test/example/recorder_feature.go
Labels: approved, cla: yes, lgtm, size/XL

#50 Expose all the parameters of the event sender in eventshub
  pkg/eventshub/options.go
  pkg/test_images/eventshub/sender/sender.go
Labels: approved, cla: yes, lgtm, size/L

#49 Sequencestepper is not used anymore
  images/sequencestepper/main.go
Labels: approved, cla: yes, lgtm, size/M

#55 Enable `Example` type tests for local yaml templates.
  pkg/eventshub/100-sa.yaml
  pkg/eventshub/101-rbac.yaml
  pkg/eventshub/102-service.yaml
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/resources.go
  pkg/manifest/templates.go
  test/example/config/echo/echo_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#56 Sort the filenames for yaml output
  pkg/eventshub/eventshub_test.go
  pkg/manifest/templates.go
Labels: approved, cla: yes, kind/cleanup, lgtm, size/M

#57 adding IsReady for downstream usage
  pkg/k8s/steps.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#59 add isAddressable, improve isReady
  pkg/k8s/steps.go
  pkg/k8s/wait.go
  test/example/recorder_feature.go
Labels: approved, cla: yes, lgtm, size/L

#60 KResource has address as a pointer, test it for nil
  pkg/k8s/steps.go
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#52 Running constraints of different timings
  pkg/environment/magic.go
  pkg/feature/collapse.go
  test/e2e/environment_test.go
  test/e2e/main_test.go
Labels: approved, cla: yes, lgtm, size/L

#61 Add utility to return the address of an Addressable.
  pkg/eventshub/options.go
  pkg/k8s/steps.go
Labels: approved, cla: yes, lgtm, size/M
