Repository knative-extensions/reconciler-test, pull requests merged in 2020-10, with the labels that each got.

#19 Add tayarani as reviewer
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#17 conformance lib poc
  pkg/test/context.go
  pkg/test/context_test.go
  pkg/test/environment/cluster.go
  pkg/test/environment/images.go
  pkg/test/environment/ingress.go
  pkg/test/environment/spoof.go
  pkg/test/feature/states.go
  pkg/test/feature/states_test.go
  pkg/test/requirement/level.go
  pkg/test/requirement/level_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#20 support configuring cluster domains
  pkg/test/environment/cluster.go
Labels: approved, cla: yes, lgtm, size/S

#25 Change how we default feature states & requirement levels
  pkg/test/context.go
  pkg/test/context_test.go
Labels: approved, cla: yes, lgtm, size/S

#26 Include a default parent context
  pkg/test/context.go
Labels: approved, cla: yes, lgtm, size/XS

#28 rename Context to C
  pkg/test/context.go
Labels: approved, cla: yes, lgtm, size/S
