Repository knative-extensions/reconciler-test, pull requests merged in 2020-09, with the labels that each got.

#1 use a real presubmit
  OWNERS_ALIASES
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#4 add github actions
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
  hack/update-codegen.sh
Labels: approved, cla: yes, lgtm, size/L

#13 move sample test suite to test/sample
  test/sample/suite_test.go
  test/sample/test-config.yaml
Labels: approved, cla: yes, lgtm, size/XS

#10 Observer test code
  go.mod
  images/recorder/main.go
  images/sequencestepper/main.go
  pkg/components/sequencestepper/sequencestepper.go
  pkg/observer/doc.go
  pkg/observer/eventlog.go
  pkg/observer/http-vent/doc.go
  pkg/observer/http-vent/http.go
  pkg/observer/observation.go
  pkg/observer/observer.go
  pkg/observer/recorder-collector/collector.go
  pkg/observer/recorder-collector/doc.go
  pkg/observer/recorder-vent/constructor.go
  pkg/observer/recorder-vent/doc.go
  pkg/observer/recorder-vent/recorder.go
  pkg/observer/writer-vent/doc.go
  pkg/observer/writer-vent/writer.go
  third_party/VENDOR-LICENSE/knative.dev/reconciler-test/LICENSE
  vendor/knative.dev/pkg/system/testing/names.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL
