Repository knative-extensions/reconciler-test, pull requests merged in 2021-05, with the labels that each got.

#190 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
  hack/OWNERS
Labels: approved, cla: yes, lgtm

#186 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#195 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#200 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#198 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#197 Add Kafka projects to downstream tests
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/XS

#199 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#201 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#204 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#207 Add a way to manually add event assertions
  pkg/eventshub/prober.go
Labels: approved, cla: yes, lgtm, size/XS

#196 Use go 1.16 embed for templates
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-downstream.yaml
  README.md
  go.mod
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/resources.go
  pkg/manifest/installer.go
  pkg/manifest/templates.go
  resources/svc/service.go
  resources/svc/service_test.go
  test/example/config/echo/echo.go
  test/example/config/echo/echo_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#205 Fix redundant name in Assert helper
  pkg/feature/feature.go
Labels: approved, cla: yes, lgtm, size/S
