Repository knative-extensions/reconciler-test, pull requests merged in 2021-01, with the labels that each got.

#68 Fix ko setup
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#67 eventshub.Install docs
  pkg/eventshub/resources.go
Labels: approved, cla: yes, lgtm, size/S

#70 Update to fix releasability
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#71 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#72 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#74 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#76 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/code-generator/SECURITY_CONTACTS
  vendor/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/scheme/generator_for_scheme.go
  vendor/k8s.io/code-generator/cmd/client-gen/main.go
  vendor/k8s.io/code-generator/cmd/conversion-gen/generators/conversion.go
  vendor/k8s.io/code-generator/cmd/conversion-gen/main.go
  vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go
  vendor/k8s.io/code-generator/cmd/defaulter-gen/main.go
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/generator.go
  vendor/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/tags.go
  vendor/k8s.io/code-generator/cmd/import-boss/README.md
  vendor/k8s.io/code-generator/cmd/import-boss/main.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/factory.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/factoryinterface.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/generic.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/informer.go
  vendor/k8s.io/code-generator/cmd/informer-gen/generators/packages.go
  vendor/k8s.io/code-generator/cmd/informer-gen/main.go
  vendor/k8s.io/code-generator/cmd/lister-gen/.import-restrictions
  vendor/k8s.io/code-generator/cmd/lister-gen/generators/lister.go
  vendor/k8s.io/code-generator/cmd/lister-gen/main.go
  vendor/k8s.io/code-generator/cmd/openapi-gen/main.go
  vendor/k8s.io/code-generator/cmd/register-gen/generators/packages.go
  vendor/k8s.io/code-generator/cmd/register-gen/main.go
  vendor/k8s.io/code-generator/cmd/set-gen/main.go
  vendor/k8s.io/code-generator/go.mod
  vendor/k8s.io/code-generator/go.sum
  vendor/k8s.io/gengo/parser/parse.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#75 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#62 DSL to perform assertions on eventshub store
  pkg/eventshub/event_info_matchers.go
  pkg/eventshub/event_info_store.go
  pkg/eventshub/step.go
  test/example/recorder_feature.go
Labels: approved, cla: yes, lgtm, size/L
