Repository knative-extensions/reconciler-test, pull requests merged in 2021-12, with the labels that each got.

#261 Test scoped logs in wait functions
  pkg/k8s/job.go
  pkg/k8s/steps.go
  pkg/k8s/wait.go
  test/example/echo_feature.go
Labels: cla: yes, lgtm, approved, kind/bug, size/M

#258 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, approved, size/M

#257 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/M

#262 Add log milestone emitter
  pkg/environment/interfaces.go
  pkg/environment/magic.go
  pkg/milestone/emitter_composite.go
  pkg/milestone/emitter_log.go
  pkg/milestone/factory.go
Labels: cla: yes, lgtm, approved, kind/enhancement, size/L

#263 Use foreground propagation when deleting resources
  pkg/feature/feature.go
Labels: cla: yes, lgtm, approved, kind/enhancement, size/M

#267 Use t.Log instead of log.Println for test scoped logging
  pkg/eventshub/prober.go
  pkg/k8s/steps.go
Labels: lgtm, approved, size/M
