Repository knative-extensions/reconciler-test, pull requests merged in 2021-11, with the labels that each got.

#252 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#253 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/XS, lgtm, approved

#254 Backport deps to release-1.0
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, lgtm, approved, size/M

#260 Retry on webhook EOF errors
  pkg/manifest/installer.go
Labels: cla: yes, size/S, lgtm, approved, kind/bug

#259 isReady verifies resource generation and observed generation
  pkg/k8s/wait.go
Labels: cla: yes, size/XS, lgtm, approved, kind/bug
