Repository knative-extensions/reconciler-test, pull requests merged in 2021-02, with the labels that each got.

#79 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#80 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#83 Improve eventshub assertions UX
  pkg/eventshub/assert/doc.go
  pkg/eventshub/assert/event_info_matchers.go
  pkg/eventshub/assert/step.go
  pkg/eventshub/event_info_store.go
  pkg/eventshub/options.go
  test/example/recorder_feature.go
Labels: approved, cla: yes, lgtm, size/L

#85 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#84 Remove @Harwayne from OWNERS.
  OWNERS_ALIASES
Labels: approved, cla: yes, kind/removal, lgtm, size/XS

#87 Re-exporting EventInfo
  pkg/eventshub/assert/event_info_matchers.go
Labels: approved, cla: yes, lgtm, size/XS

#88 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#89 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#90 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#92 Added myself between wg-leads
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#93 Update owner aliases with modern data
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#94 remove trailing ws
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#95 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#86 Allow to specify platform for reconciler test
  pkg/images/ko.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#96 Context cancelling should be tied to the single test execution
  pkg/environment/magic.go
Labels: approved, cla: yes, lgtm, size/XS

#101 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#98 Some fixes to improve error logging
  pkg/images/cmd.go
  pkg/knative/logging_config.go
Labels: approved, cla: yes, lgtm, size/XS
