Repository knative-extensions/reconciler-test, pull requests merged in 2021-03, with the labels that each got.

#104 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#102 Adding FeatureSet and TestSet
  README.md
  pkg/environment/interfaces.go
  pkg/environment/magic.go
  pkg/feature/feature.go
  test/e2e/environment_test.go
  test/example/config/echo/echo.go
  test/example/config/echo/echo.yaml
  test/example/config/echo/echo_test.go
  test/example/echo_feature.go
  test/example/examples_test.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#105 Add feature.T interface
  pkg/eventshub/assert/step.go
  pkg/eventshub/event_info_store.go
  pkg/eventshub/resources.go
  pkg/feature/collapse.go
  pkg/feature/feature.go
  pkg/feature/t.go
  pkg/k8s/steps.go
  pkg/k8s/wait.go
  test/e2e/environment_test.go
  test/example/config/echo/echo.go
  test/example/echo_feature.go
Labels: approved, cla: yes, lgtm, size/L

#107 adding known downstreams for reconciler-test
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/M

#103 enable saving config between steps in a single feature
  pkg/environment/magic.go
  pkg/feature/feature.go
  pkg/state/context.go
  pkg/state/interfaces.go
  pkg/state/kvstore.go
  pkg/state/kvstore_test.go
  test/example/recorder_feature.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#108 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#111 Automatic feature name
  pkg/feature/feature.go
  pkg/feature/feature_test.go
Labels: approved, cla: yes, lgtm, size/M

#110 [eventshub] Add response wait time
  pkg/eventshub/options.go
  pkg/test_images/eventshub/receiver/receiver.go
Labels: approved, cla: yes, lgtm, size/M

#113 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#115 Fix Github actions
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/M

#112 Serialize stepfn execution
  pkg/environment/execution.go
  pkg/environment/magic.go
  pkg/environment/t.go
  pkg/feature/collapse.go
  test/e2e/environment_test.go
Labels: approved, cla: yes, lgtm, size/L

#114 Added feature.Assert shortcut
  pkg/feature/feature.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/XS

#109 Adding milestone events to reconciler test framework.
  README.md
  pkg/environment/magic.go
  pkg/environment/namespace.go
  pkg/milestone/emitter.go
  pkg/milestone/factory.go
  test/e2e/environment_test.go
  test/example/echo_feature.go
  test/example/recorder_feature.go
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#116 Fix milestone events for new execution phases
  pkg/environment/magic.go
  pkg/environment/t.go
  pkg/feature/t.go
  pkg/milestone/emitter.go
  pkg/milestone/factory.go
  test/e2e/environment_fails_test.go
  test/e2e/environment_test.go
Labels: approved, cla: yes, lgtm, size/L

#117 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#119 More refactoring for the execution
  pkg/environment/execution.go
  pkg/environment/magic.go
  pkg/environment/t.go
  pkg/feature/t.go
  test/e2e/environment_fails_test.go
  test/e2e/environment_test.go
Labels: approved, cla: yes, lgtm, size/L

#120 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#125 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#126 add InNamespace option for pre-existing namespace tests
  pkg/environment/magic.go
Labels: approved, cla: yes, lgtm, size/S

#123 auto manage lifecycle of env
  README.md
  pkg/environment/magic.go
  test/e2e/environment_fails_test.go
  test/e2e/environment_test.go
  test/example/examples_test.go
Labels: approved, cla: yes, lgtm, size/M

#127 adding helper to wait for an address for a resource.
  pkg/environment/magic.go
  pkg/environment/namespace.go
  pkg/environment/t.go
  pkg/environment/timings.go
  pkg/k8s/job.go
  pkg/k8s/steps.go
  pkg/k8s/wait.go
  test/example/echo_feature.go
  test/example/examples_test.go
Labels: approved, cla: yes, lgtm, size/L

#128 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#129 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#131 add variant of install from other places
  pkg/manifest/installer.go
Labels: approved, cla: yes, lgtm, size/S

#133 [Automated] Update actions
  .github/workflows/knative-security.yaml
Labels: approved, cla: yes, lgtm, size/XS

#134 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/google/gofuzz/.travis.yml
  vendor/github.com/google/gofuzz/CONTRIBUTING.md
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/bytesource/bytesource.go
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#138 fix some pasta on PollTimingsFromContext
  pkg/environment/timings.go
Labels: approved, cla: yes, lgtm, size/XS

#140 fix issue where conditions are empty
  pkg/k8s/wait.go
Labels: approved, cla: yes, lgtm, size/XS

#143 Use test as prefix for test namespaces
  pkg/environment/magic.go
Labels: approved, cla: yes, lgtm, size/XS

#145 adding common signature for config options, export PollTimings
  pkg/k8s/job.go
  pkg/k8s/steps.go
  pkg/k8s/wait.go
  pkg/manifest/installer.go
Labels: approved, cla: yes, lgtm, size/M

#144 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#148 add id for correlation
  pkg/test_images/eventshub/event_info.go
  pkg/test_images/eventshub/sender/sender.go
Labels: approved, cla: yes, lgtm, size/XS

#141 [eventshub] Define the method to send http requests and drop events
  pkg/eventshub/options.go
  pkg/test_images/eventshub/dropevents/receiver.go
  pkg/test_images/eventshub/receiver/receiver.go
  pkg/test_images/eventshub/sender/sender.go
Labels: approved, area/eventshub, cla: yes, kind/enhancement, lgtm, size/M

#149 [eventshub] Fix #148
  pkg/test_images/eventshub/event_info.go
  pkg/test_images/eventshub/sender/sender.go
Labels: approved, cla: yes, lgtm, size/S

#147 [eventshub] Override time when sending events
  pkg/eventshub/options.go
  pkg/test_images/eventshub/sender/sender.go
Labels: approved, area/eventshub, cla: yes, kind/enhancement, lgtm, size/XS

#153 rename downstream-test-go to actions-downstream-test
  .github/workflows/knative-downstream.yaml
Labels: approved, cla: yes, lgtm, size/XS

#142 Now stepfn can panic safely
  pkg/environment/execution.go
  pkg/environment/magic.go
  test/e2e/environment_fails_test.go
Labels: approved, cla: yes, lgtm, size/L

#155 print all the headers, including ce-*
  pkg/test_images/eventshub/event_info.go
  pkg/test_images/eventshub/sender/sender.go
Labels: approved, cla: yes, lgtm, size/XS

#156 Hunting the panic issue
  pkg/environment/execution.go
  pkg/environment/magic.go
  test/e2e/environment_test.go
Labels: approved, bug, cla: yes, lgtm, size/M

#154 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#157 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#158 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S
