Repository knative-extensions/reconciler-test, pull requests merged in 2021-04, with the labels that each got.

#160 drop pkg/test, not used.
  pkg/test/context.go
  pkg/test/context_test.go
  pkg/test/environment/cluster.go
  pkg/test/environment/images.go
  pkg/test/environment/ingress.go
  pkg/test/environment/spoof.go
  pkg/test/feature/states.go
  pkg/test/feature/states_test.go
  pkg/test/requirement/level.go
  pkg/test/requirement/level_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#161 export the collected events
  pkg/eventshub/event_info_store.go
Labels: approved, cla: yes, lgtm, size/XS

#162 [main] Upgrade to latest dependencies
  vendor/knative.dev/pkg/test/helpers/dir.go
  vendor/knative.dev/pkg/test/helpers/dryrun.go
  vendor/knative.dev/pkg/test/helpers/error.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#163 [EventsHub] Refactor sender to use a generator
  pkg/test_images/eventshub/sender/sender.go
Labels: approved, cla: yes, lgtm, size/L

#164 do not use t outside of test
  pkg/eventshub/assert/step.go
  pkg/eventshub/event_info_store.go
  test/example/recorder_feature.go
Labels: approved, cla: yes, lgtm, size/M

#171 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/network/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#170 add debug to failed start pods
  pkg/k8s/wait.go
Labels: approved, cla: yes, lgtm, size/S

#172 move eventshub to single dir
  cmd/eventshub/main.go
  go.sum
  pkg/eventshub/assert/event_info_matchers.go
  pkg/eventshub/dropevents/dropeventsfibonacci/fibonacci.go
  pkg/eventshub/dropevents/dropeventsfirst/sequence.go
  pkg/eventshub/dropevents/receiver.go
  pkg/eventshub/event_info.go
  pkg/eventshub/event_info_store.go
  pkg/eventshub/event_log.go
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/logger_vent/logger.go
  pkg/eventshub/options.go
  pkg/eventshub/receiver/receiver.go
  pkg/eventshub/receiver/reply.go
  pkg/eventshub/recorder_vent/constructor.go
  pkg/eventshub/recorder_vent/doc.go
  pkg/eventshub/recorder_vent/recorder.go
  pkg/eventshub/resources.go
  pkg/eventshub/sender/sender.go
  pkg/eventshub/utils.go
  pkg/k8s/wait.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/cleanup.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/crd.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/flags/e2e_flags.go
  vendor/knative.dev/pkg/test/ingress/ingress.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/pkg/test/monitoring/doc.go
  vendor/knative.dev/pkg/test/monitoring/monitoring.go
  vendor/knative.dev/pkg/test/presubmit-tests.sh
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/pkg/test/test-reconciler-codegen.sh
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#173 Adding Event Prober lib that wrapps eventhub into an instance.
  pkg/eventshub/prober.go
  resources/svc/service.go
  resources/svc/service.yaml
  resources/svc/service_test.go
  test/example/examples_test.go
  test/example/prober_feature.go
  test/example/recorder_feature.go
Labels: approved, cla: yes, lgtm, size/XL

#174 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#175 Adding prober reject settings and examples.
  pkg/eventshub/prober.go
  test/example/examples_test.go
  test/example/prober_feature.go
Labels: approved, cla: yes, lgtm, size/L

#176 update to new release of golang sdk for cloudevents 2.4.1
  go.mod
  go.sum
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v03_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1.go
  vendor/github.com/cloudevents/sdk-go/v2/event/eventcontext_v1_reader.go
  vendor/github.com/cloudevents/sdk-go/v2/event/extensions.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#178 Implement step planning event
  pkg/environment/magic.go
  pkg/milestone/emitter.go
  pkg/milestone/factory.go
Labels: cla: yes, size/M

#182 Fail on feature.Require errors.
  README.md
  pkg/environment/magic.go
  test/e2e/environment_fails_test.go
  test/e2e/environment_test.go
Labels: approved, cla: yes, lgtm, size/L

#183 add feature to context, add refs to feature
  pkg/environment/magic.go
  pkg/feature/context.go
  pkg/feature/feature.go
  pkg/manifest/installer.go
Labels: approved, cla: yes, lgtm, size/M

#159 document Store and KVStore
  README.md
Labels: approved, cla: yes, lgtm, size/M

#187 fix tiny README typos
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#188 #180 add flag to allow filtering of features while running tests
  README.md
  pkg/environment/flags.go
  pkg/environment/magic.go
  test/e2e/main_test.go
Labels: approved, cla: yes, lgtm, size/M

#185 Delete feature resources
  pkg/feature/feature.go
  test/example/echo_feature.go
Labels: approved, cla: yes, lgtm, size/S

#189 [Automated] Format markdown
  README.md
Labels: approved, cla: yes, lgtm, size/XS
