Repository knative-extensions/reconciler-test, pull requests merged in 2022-02, with the labels that each got.

#290 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved

#288 Wait for resource deletions in DeleteResources
  pkg/feature/feature.go
  pkg/feature/logging.go
Labels: lgtm, approved, size/L

#302 Add EventHub readiness probe only in the receiver role
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/resources.go
Labels: lgtm, approved, kind/bug, size/M

#293 Auto logging on teardown
  pkg/environment/logging.go
  pkg/environment/magic.go
Labels: lgtm, approved, size/M

#300 Features are stored by reference in a FeatureSet
  pkg/environment/magic.go
  pkg/feature/feature.go
  test/example/echo_feature.go
Labels: size/S, lgtm, approved, kind/bug
