Repository knative-extensions/reconciler-test, pull requests merged in 2022-06, with the labels that each got.

#347 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#348 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#349 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#350 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#352 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#353 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#354 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#351 Bump kind to v0.14 for e2e tests
  .github/workflows/kind-e2e.yaml
Labels: size/XS, lgtm, approved
