Repository knative-extensions/reconciler-test, pull requests merged in 2022-11, with the labels that each got.

#409 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/ptr/doc.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#416 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#419 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#415 Use knative/actions downstream test
  .github/workflows/knative-downstream.yaml
Labels: lgtm, approved, size/M

#417 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/duck/verify.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/configmap/doc.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/hash/doc.go
  vendor/knative.dev/pkg/injection/doc.go
  vendor/knative.dev/pkg/injection/injection.go
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/reconciler/retry.go
  vendor/knative.dev/pkg/test/gcs/gcs.go
  vendor/knative.dev/pkg/test/zipkin/doc.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/knative.dev/pkg/tracing/opencensus.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#414 Define SecurityContext for test Pods
  go.mod
  go.sum
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/resources.go
  pkg/k8s/pod.go
  pkg/manifest/options.go
  vendor/knative.dev/pkg/test/security/security.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#420 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#421 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#422 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/sets/byte.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int.go
  vendor/k8s.io/gengo/examples/set-gen/sets/int64.go
  vendor/k8s.io/gengo/examples/set-gen/sets/string.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/namer/import_tracker.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#423 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#424 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/infra-library.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved
