Repository knative-extensions/reconciler-test, pull requests merged in 2022-08, with the labels that each got.

#369 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#370 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#371 Fix String() call on nil events on event sender
  pkg/eventshub/sender/sender.go
Labels: size/XS, lgtm, approved, kind/bug

#372 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#373 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#374 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#364 Bump go to v1.18 and update deps
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-downstream.yaml
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#376 Properly shutdown tracer to flush Spans
  pkg/eventshub/eventshub.go
  pkg/eventshub/utils.go
Labels: size/S, lgtm, approved

#379 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#378 Cleanup github action
  .github/workflows/go-test-windows.yaml
  .github/workflows/knative-downstream.yaml
  .vscode
Labels: size/XS, lgtm, approved

#380 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#381 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#388 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved
