Repository knative-extensions/reconciler-test, pull requests merged in 2022-10, with the labels that each got.

#402 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#403 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#404 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#405 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#411 Fix data race on publish images
  pkg/environment/images.go
  pkg/environment/images_test.go
Labels: lgtm, approved, kind/bug, size/M
