Repository knative-extensions/reconciler-test, pull requests merged in 2022-05, with the labels that each got.

#335 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#334 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#336 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#338 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#339 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#340 Remove calling ExecuteLocalYAML func, b/c it is deprecated
  pkg/manifest/templates.go
Labels: size/S, lgtm, approved

#341 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#343 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#344 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#342 [main] Format markdown
  CODE-OF-CONDUCT.md
  README.md
Labels: size/S, lgtm, approved
