Repository knative-extensions/reconciler-test, pull requests merged in 2022-01, with the labels that each got.

#255 added assertReceivedNone function to reconciler-test prober
  pkg/eventshub/prober.go
Labels: cla: yes, size/S, lgtm, approved

#264 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved

#265 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#275 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#277 Improve logging for features and their state
  pkg/environment/magic.go
  pkg/feature/feature.go
  pkg/feature/feature_test.go
  pkg/feature/level.go
  pkg/feature/states.go
  pkg/feature/timing.go
  pkg/state/kvstore.go
Labels: lgtm, approved, size/L

#278 Log pod state while waiting for pod to be ready
  pkg/k8s/wait.go
Labels: size/S, lgtm, approved

#274 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#279 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#283 Actually log pod logs on error waiting to become ready
  pkg/k8s/wait.go
Labels: size/XS, lgtm, approved

#282 Remove log emitter noise
  pkg/milestone/emitter_log.go
Labels: size/S, lgtm, approved

#281 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, lgtm, approved

#285 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#286 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#289 Use Go 1.17 for downstream tests
  .github/workflows/knative-downstream.yaml
Labels: size/XS, lgtm, approved

#287 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved
