Repository knative-extensions/reconciler-test, pull requests merged in 2022-07, with the labels that each got.

#355 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#356 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#357 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#358 [eventshub] Allow defining a custom response body for skipped events
  pkg/eventshub/receiver/receiver.go
Labels: size/XS, lgtm, approved, kind/enhancement

#359 Add DropEventsResponseBody EventsHubOption
  pkg/eventshub/options.go
Labels: size/XS, lgtm, approved

#360 Dump collected events on failed matches
  pkg/eventshub/event_info_store.go
Labels: size/S, lgtm, approved

#362 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#294 :broom: Logging overhaul
  .github/workflows/kind-e2e.yaml
  .github/workflows/knative-downstream.yaml
  README.md
  go.mod
  go.sum
  pkg/environment/images.go
  pkg/environment/interfaces.go
  pkg/environment/logging.go
  pkg/environment/magic.go
  pkg/environment/standard.go
  pkg/eventshub/event_info_store.go
  pkg/eventshub/eventshub_image.go
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/rbac/rbac_test.go
  pkg/eventshub/resources.go
  pkg/feature/feature.go
  pkg/images/ko/cmd.go
  pkg/images/ko/publish.go
  pkg/k8s/pod.go
  pkg/k8s/pod_test.go
  pkg/k8s/wait.go
  pkg/logging/context.go
  pkg/logging/env.go
  pkg/logging/env_test.go
  pkg/manifest/installer.go
  pkg/manifest/logging.go
  pkg/manifest/manifest.go
  pkg/manifest/templates.go
  pkg/milestone/emitter.go
  pkg/milestone/emitter_composite.go
  pkg/milestone/emitter_log.go
  resources/svc/service_test.go
  test/e2e-tests.sh
  test/e2e/eventshub/main_test.go
  test/e2e/eventshub/receiver_readiness.go
  test/e2e/main_test.go
  test/example/config/echo/echo.go
  test/example/config/echo/echo_test.go
  test/example/examples_test.go
  test/example/ko_publish_test.go
  test/example/main_test.go
  third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  vendor/go.uber.org/zap/internal/ztest/doc.go
  vendor/go.uber.org/zap/internal/ztest/timeout.go
  vendor/go.uber.org/zap/internal/ztest/writer.go
  vendor/go.uber.org/zap/zaptest/doc.go
  vendor/go.uber.org/zap/zaptest/logger.go
  vendor/go.uber.org/zap/zaptest/testingt.go
  vendor/go.uber.org/zap/zaptest/timeout.go
  vendor/go.uber.org/zap/zaptest/writer.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, kind/cleanup

#361 :bug: Eventshub tests work on Windows
  .github/workflows/go-test-windows.yaml
  pkg/manifest/installer.go
  pkg/manifest/manifest.go
  pkg/manifest/manifest_test.go
  pkg/manifest/templates.go
  pkg/manifest/templates_test.go
  pkg/manifest/testdata/100-ns.yaml
  pkg/manifest/testdata/101-pod.yaml
  pkg/manifest/yaml.go
Labels: lgtm, approved, size/L, kind/bug

#365 :wastebasket: Removal of deprecated, unused functions.
  pkg/environment/magic.go
  pkg/manifest/installer.go
Labels: lgtm, approved, kind/cleanup, size/M
