Repository knative-extensions/reconciler-test, pull requests merged in 2022-03, with the labels that each got.

#298 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#291 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/M

#304 Retry on context deadline exceeded errors
  pkg/manifest/installer.go
Labels: size/S, lgtm, approved

#308 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#309 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#310 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/hash/bucketer.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#313 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/XS, lgtm, approved

#317 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/XL

#318 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#316 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, lgtm, approved
