Repository knative-extensions/reconciler-test, pull requests merged in 2023-10, with the labels that each got.

#596 Update to golang 1.20
  .github/workflows/go-test-windows.yaml
  .github/workflows/kind-e2e.yaml
  go.mod
Labels: size/XS, lgtm, approved

#598 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#599 Fix forwarder SINK URL
  pkg/eventshub/resources.go
  pkg/manifest/manifest.go
Labels: size/S, lgtm, approved, kind/bug

#595 Support OIDC in eventshub sender
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/assert/step.go
  pkg/eventshub/event_info_store.go
  pkg/eventshub/options.go
  pkg/eventshub/resources.go
  pkg/eventshub/sender/sender.go
  pkg/eventshub/utils.go
  pkg/resources/serviceaccount/serviceaccount.go
  pkg/resources/serviceaccount/serviceaccount.yaml
  pkg/resources/serviceaccount/serviceaccount_test.go
Labels: lgtm, approved, size/L

#603 Use base64URL en-/decoder from std lib
  pkg/eventshub/resources.go
Labels: size/S, lgtm, approved

#604 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/server.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#607 Enable OIDCAuth for eventshub sender when sink has an audience
  pkg/eventshub/options.go
  pkg/eventshub/utils.go
Labels: size/S, lgtm, approved

#608 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#609 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#612 Support OIDC in eventshub receiver
  .github/workflows/kind-e2e.yaml
  pkg/eventshub/options.go
  pkg/eventshub/rbac/101-rbac.yaml
  pkg/eventshub/receiver/receiver.go
  pkg/eventshub/utils.go
  test/e2e-tests.sh
  test/e2e/eventshub/oidc_test.go
Labels: lgtm, approved, size/L

#616 Improve logging message when deleting resources
  pkg/feature/feature.go
  pkg/feature/logging.go
Labels: size/S, lgtm, approved

#621 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#620 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#622 [release-1.12] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#613 Use ParallelTest*() for OIDC tests
  test/e2e/eventshub/oidc_test.go
Labels: size/XS, lgtm, approved

#624 Configure sender with CA certs when provided
  pkg/eventshub/sender/sender.go
Labels: size/XS, lgtm, approved
