Repository knative-extensions/reconciler-test, pull requests merged in 2023-09, with the labels that each got.

#580 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#581 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#582 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#583 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#585 Option to override namespace for magic environment
  pkg/environment/magic.go
  pkg/environment/namespace.go
Labels: size/XS, lgtm, approved

#591 :lady_beetle: Call the Istio' quit when the eventshub is closed
  pkg/eventshub/eventshub.go
  pkg/eventshub/istio_quit.go
Labels: lgtm, approved, kind/bug, size/M

#584 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
