Repository knative-extensions/reconciler-test, pull requests merged in 2023-05, with the labels that each got.

#518 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#517 Knative Service forwarder for EventsHub
  cmd/eventshub/main.go
  pkg/eventshub/102-service.yaml
  pkg/eventshub/104-forwarder.yaml
  pkg/eventshub/event_log.go
  pkg/eventshub/eventshub_image.go
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/forwarder/forwarder.go
  pkg/eventshub/options.go
  pkg/eventshub/resources.go
  pkg/eventshub/sender/sender.go
  pkg/eventshub/utils.go
  pkg/resources/knativeservice/ksvc.go
Labels: lgtm, approved, size/XL

#515 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#519 Remove resources when terminating the environment
  pkg/environment/magic.go
  pkg/feature/feature.go
Labels: lgtm, approved, size/M

#523 Add support for feature-level prerequisites
  pkg/environment/execution.go
  pkg/environment/magic.go
  pkg/feature/feature.go
  pkg/feature/timing.go
  pkg/milestone/emitter_log.go
  test/e2e/environment_test.go
Labels: lgtm, approved, size/L

#528 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/text/cases/cases.go
  vendor/golang.org/x/text/cases/context.go
  vendor/golang.org/x/text/cases/fold.go
  vendor/golang.org/x/text/cases/icu.go
  vendor/golang.org/x/text/cases/info.go
  vendor/golang.org/x/text/cases/map.go
  vendor/golang.org/x/text/cases/tables10.0.0.go
  vendor/golang.org/x/text/cases/tables11.0.0.go
  vendor/golang.org/x/text/cases/tables12.0.0.go
  vendor/golang.org/x/text/cases/tables13.0.0.go
  vendor/golang.org/x/text/cases/tables9.0.0.go
  vendor/golang.org/x/text/cases/trieval.go
  vendor/golang.org/x/text/internal/internal.go
  vendor/golang.org/x/text/internal/language/common.go
  vendor/golang.org/x/text/internal/language/compact.go
  vendor/golang.org/x/text/internal/language/compact/compact.go
  vendor/golang.org/x/text/internal/language/compact/language.go
  vendor/golang.org/x/text/internal/language/compact/parents.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/compact/tags.go
  vendor/golang.org/x/text/internal/language/compose.go
  vendor/golang.org/x/text/internal/language/coverage.go
  vendor/golang.org/x/text/internal/language/language.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/match.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/language/tags.go
  vendor/golang.org/x/text/internal/match.go
  vendor/golang.org/x/text/internal/tag/tag.go
  vendor/golang.org/x/text/language/coverage.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/language.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/language/tags.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#530 Improve receiver TLS verification
  pkg/eventshub/event_info.go
  pkg/eventshub/receiver/receiver.go
Labels: lgtm, approved, size/M

#529 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#533 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#536 Eventshub forwarders properly forwards body/data
  pkg/eventshub/forwarder/forwarder.go
Labels: size/XS, lgtm, approved

#537 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#538 eventshub RBAC resources independent to avoid deletion conflicts
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/104-forwarder.yaml
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/rbac/100-sa.yaml
  pkg/eventshub/rbac/101-rbac.yaml
  pkg/eventshub/rbac/rbac.go
  pkg/eventshub/rbac/rbac_test.go
  pkg/eventshub/resources.go
Labels: lgtm, approved, size/M
