Repository knative-extensions/reconciler-test, pull requests merged in 2023-03, with the labels that each got.

#491 Allow specifying parallel tests for parallelizable features
  pkg/environment/interfaces.go
  pkg/environment/magic.go
  test/e2e/environment_test.go
Labels: lgtm, approved, size/M

#492 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#493 Set port name to service
  pkg/resources/service/service.go
Labels: size/XS, lgtm, approved

#494 Move service port defaulting to config defaults
  pkg/resources/service/service.go
Labels: size/S, lgtm, approved

#495 Allow using a prespecified namespace for running tests
  README.md
  pkg/environment/flags.go
  pkg/environment/magic.go
  pkg/environment/namespace.go
  pkg/environment/standard.go
Labels: lgtm, approved, size/M

#496 Support cronjobs
  pkg/environment/images.go
  pkg/feature/feature.go
  pkg/resources/cronjob/cronjob.go
  pkg/resources/cronjob/cronjob.yaml
  pkg/resources/cronjob/cronjob_test.go
  pkg/resources/cronjob/options.go
  test/e2e/resources_test.go
Labels: lgtm, approved, size/XL

#498 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#499 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#500 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review
