Repository knative-extensions/reconciler-test, pull requests merged in 2023-02, with the labels that each got.

#452 Add helpers to create & interact with a batchv1.Job
  pkg/k8s/job.go
  pkg/resources/job/job.go
  pkg/resources/job/job.yaml
  pkg/resources/job/job_test.go
  pkg/resources/job/options.go
Labels: lgtm, approved, size/XL, kind/enhancement

#453 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#454 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#455 Add helpers to create & interact with a Secret
  pkg/resources/secret/options.go
  pkg/resources/secret/secret.go
  pkg/resources/secret/secret.yaml
  pkg/resources/secret/secret_test.go
Labels: lgtm, approved, kind/enhancement, size/L

#457 Add helpers to work with the service resource
  pkg/resources/service/options.go
  pkg/resources/service/service.go
  pkg/resources/service/service.yaml
  pkg/resources/service/service_test.go
  resources/svc/service.go
  resources/svc/service.yaml
  resources/svc/service_test.go
Labels: lgtm, approved, size/XL, kind/enhancement

#456 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#458 Add Pod resource
  pkg/manifest/options.go
  pkg/resources/job/job_test.go
  pkg/resources/job/options.go
  pkg/resources/pod/options.go
  pkg/resources/pod/pod.go
  pkg/resources/pod/pod.yaml
  pkg/resources/pod/pod_test.go
  pkg/resources/secret/options.go
  pkg/resources/secret/secret_test.go
  pkg/resources/service/options.go
  pkg/resources/service/service_test.go
Labels: lgtm, approved, size/XL, kind/enhancement

#461 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#462 Add Deployment resource
  pkg/resources/deployment/deployment.go
  pkg/resources/deployment/deployment.yaml
  pkg/resources/deployment/deployment_test.go
  pkg/resources/deployment/options.go
Labels: lgtm, approved, size/XL

#463 Add option to set selector on deployment resource
  pkg/resources/deployment/deployment_test.go
  pkg/resources/deployment/options.go
Labels: lgtm, approved, size/M

#464 Add Namespace resource
  pkg/resources/namespace/namespace.go
  pkg/resources/namespace/namespace.yaml
  pkg/resources/namespace/namespace_test.go
Labels: lgtm, approved, kind/enhancement, size/L

#465 Add file-based image resolver
  README.md
  pkg/environment/flags.go
  pkg/environment/images.go
  pkg/environment/images_test.go
  pkg/environment/standard.go
  pkg/environment/testdata/images.yaml
  pkg/images/file/file.go
  pkg/images/file/file_test.go
  pkg/images/file/testdata/images.yaml
Labels: lgtm, approved, size/L

#470 [release-1.7] Add file-based image resolver (#465)
  README.md
  pkg/environment/flags.go
  pkg/environment/images.go
  pkg/environment/images_test.go
  pkg/environment/standard.go
  pkg/environment/testdata/images.yaml
  pkg/images/file/file.go
  pkg/images/file/file_test.go
  pkg/images/file/testdata/images.yaml
Labels: lgtm, approved, size/L

#471 Fix deployment resource image setting
  pkg/resources/deployment/deployment.go
Labels: size/XS, lgtm, approved, kind/bug

#472 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#466 Allow testing with istio enabled
  README.md
  pkg/environment/istio.go
  pkg/environment/istio_test.go
  pkg/environment/namespace.go
  pkg/environment/standard.go
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/resources.go
  pkg/manifest/options.go
  pkg/resources/deployment/deployment.go
  pkg/resources/deployment/options.go
  pkg/resources/job/job.go
  pkg/resources/job/options.go
  pkg/resources/pod/pod.go
Labels: lgtm, approved, size/L

#473 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#475 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#474 [release-1.9] Allow testing with istio enabled (#466)
  README.md
  pkg/environment/istio.go
  pkg/environment/istio_test.go
  pkg/environment/namespace.go
  pkg/environment/standard.go
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/resources.go
  pkg/manifest/options.go
Labels: lgtm, approved, size/L

#478 Allow verify service readiness when istio is installed
  pkg/k8s/wait.go
Labels: size/S, lgtm, approved

#479 Restart eventshub on failure
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/eventshub_test.go
Labels: size/XS, lgtm, approved

#476 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#485 Add teardown.on.fail flag
  pkg/environment/flags.go
  pkg/environment/magic.go
  pkg/environment/namespace.go
Labels: lgtm, approved, size/M

#484 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/M
