Repository knative-extensions/reconciler-test, pull requests merged in 2023-04, with the labels that each got.

#502 Support setting Job labels for cron jobs
  pkg/resources/cronjob/cronjob.go
  pkg/resources/cronjob/cronjob.yaml
  pkg/resources/cronjob/cronjob_test.go
Labels: size/S, lgtm, approved

#503 Quote label values for cronjob
  pkg/resources/cronjob/cronjob.yaml
  pkg/resources/cronjob/cronjob_test.go
Labels: size/S, lgtm, approved

#504 Quote label and selector values
  pkg/resources/cronjob/cronjob.yaml
  pkg/resources/cronjob/cronjob_test.go
  pkg/resources/deployment/deployment.yaml
  pkg/resources/deployment/deployment_test.go
  pkg/resources/job/job.yaml
  pkg/resources/job/job_test.go
  pkg/resources/namespace/namespace.yaml
  pkg/resources/namespace/namespace_test.go
  pkg/resources/pod/pod.yaml
  pkg/resources/pod/pod_test.go
  pkg/resources/secret/secret.yaml
  pkg/resources/secret/secret_test.go
  pkg/resources/service/service.yaml
  pkg/resources/service/service_test.go
Labels: lgtm, approved, size/M

#507 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#508 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#505 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#506 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#509 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#510 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#513 Update downstream test Go version and remove eventing-natss
  .github/workflows/knative-downstream.yaml
Labels: size/XS, lgtm, approved

#511 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#514 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
