Repository knative-extensions/reconciler-test, pull requests merged in 2023-07, with the labels that each got.

#526 Add support for sending events to HTTPS endpoints in Eventshub
  pkg/eventshub/options.go
  pkg/eventshub/prober.go
  pkg/eventshub/sender/sender.go
  pkg/k8s/steps.go
  pkg/k8s/wait.go
  pkg/resources/service/service.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/binding_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/doc.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/resolver/doc.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, ok-to-test

#545 E2E test for sender TLS support
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/options.go
  pkg/eventshub/receiver/receiver.go
  pkg/eventshub/resources.go
  pkg/eventshub/utils.go
  test/e2e/eventshub/receiver_tls_test.go
Labels: lgtm, approved, size/L

#547 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#490 Remove deprecated usage of ZipkinTracingEnabled
  pkg/milestone/emitter_tracing.go
Labels: size/XS, lgtm, approved

#548 Support matching sender received peer certificates for certs rotation testing
  pkg/eventshub/assert/step.go
  pkg/eventshub/event_info.go
  pkg/eventshub/event_info_store.go
  pkg/eventshub/receiver/receiver.go
  pkg/eventshub/sender/sender.go
  test/e2e/eventshub/receiver_tls_test.go
Labels: lgtm, approved, size/L

#552 Create a client and transport per request in the TLS case to force TLS handshakes
  pkg/eventshub/sender/sender.go
  test/e2e/eventshub/receiver_tls_test.go
Labels: lgtm, approved, size/M

#554 [release-1.10] Add name to port
  pkg/eventshub/102-service.yaml
Labels: size/XS, lgtm, approved

#556 [release-1.10] Fix unit tests
  pkg/eventshub/eventshub_test.go
Labels: size/XS, lgtm, approved
