Repository knative-extensions/reconciler-test, pull requests merged in 2023-11, with the labels that each got.

#625 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#628 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#629 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#632 Make SECURITY.md consistent
  SECURITY.md
Labels: size/XS, lgtm, approved

#636 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#635 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#637 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
