Repository knative-extensions/reconciler-test, pull requests merged in 2024-08, with the labels that each got.

#746 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/sync/LICENSE
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#747 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#750 feat: add support for verifying the event format in the eventshub receiver
  pkg/eventshub/options.go
  pkg/eventshub/receiver/receiver.go
Labels: lgtm, approved, size/M

#749 Allow to configure OIDC subject name for eventshub sender
  pkg/eventshub/options.go
  pkg/eventshub/resources.go
  pkg/eventshub/utils.go
Labels: size/XS, lgtm, approved

#751 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#753 Actually use provided namesapce in `secret.IsPresentInNamespace`
  pkg/resources/secret/secret.go
Labels: size/XS, lgtm, approved
