Repository knative-extensions/reconciler-test, pull requests merged in 2024-01, with the labels that each got.

#643 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#645 Allow testing trust-bundle integration
  README.md
  hack/update-cert-manager.sh
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/environment/namespace.go
  pkg/eventshub/105-certificate-service.yaml
  pkg/eventshub/options.go
  pkg/eventshub/resources.go
  pkg/eventshub/utils.go
  pkg/resources/secret/secret.go
  test/e2e-common.sh
  test/install.sh
  third_party/cert-manager/00-namespace.yaml
  third_party/cert-manager/01-cert-manager.yaml
  third_party/cert-manager/02-trust-manager.yaml
Labels: lgtm, approved, size/XXL

#650 Support Deployment ConfigMap volumes
  pkg/resources/deployment/deployment.yaml
  pkg/resources/deployment/deployment_test.go
  pkg/resources/deployment/options.go
Labels: lgtm, approved, size/L

#647 [release-1.11] Allow testing trust-bundle integration (#645)
  README.md
  hack/update-cert-manager.sh
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/environment/namespace.go
  pkg/eventshub/105-certificate-service.yaml
  pkg/eventshub/options.go
  pkg/eventshub/resources.go
  pkg/eventshub/utils.go
  pkg/resources/secret/secret.go
  test/e2e-common.sh
  test/install.sh
  third_party/cert-manager/00-namespace.yaml
  third_party/cert-manager/01-cert-manager.yaml
  third_party/cert-manager/02-trust-manager.yaml
Labels: lgtm, approved, size/XXL

#652 Remove kubectl dependency in hack/update-cert-manager.sh
  hack/update-cert-manager.sh
  third_party/cert-manager/00-namespace.yaml
Labels: size/S, lgtm, approved

#653 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#654 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#656 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#657 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#658 Create standard global environment with provided rest config
  pkg/environment/standard.go
Labels: size/S, lgtm, approved

#660 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/context.go
  vendor/github.com/go-logr/logr/context_noslog.go
  vendor/github.com/go-logr/logr/context_slog.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/sloghandler.go
  vendor/github.com/go-logr/logr/slogr.go
  vendor/github.com/go-logr/logr/slogsink.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/version7.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#661 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_others.go
  vendor/google.golang.org/grpc/internal/tcp_keepalive_windows.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#662 Update Golang to 1.21
  .github/workflows/go-test-windows.yaml
  .github/workflows/knative-downstream.yaml
  go.mod
  go.sum
Labels: size/S, lgtm, approved
