Repository knative-extensions/reconciler-test, pull requests merged in 2024-09, with the labels that each got.

#755 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#754 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#758 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer/pickfirst/pickfirst.go
  vendor/google.golang.org/grpc/balancer_wrapper.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/credentials/insecure/insecure.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/grpclog/internal/logger.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/channelz/channelmap.go
  vendor/google.golang.org/grpc/internal/channelz/funcs.go
  vendor/google.golang.org/grpc/internal/channelz/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/passthrough/passthrough.go
  vendor/google.golang.org/grpc/internal/status/status.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/keepalive/keepalive.go
  vendor/google.golang.org/grpc/mem/buffers.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/stream_interfaces.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#762 Use istio inject label
  pkg/eventshub/103-pod.yaml
  pkg/eventshub/104-forwarder.yaml
  pkg/eventshub/eventshub_test.go
  pkg/eventshub/resources.go
  pkg/manifest/options.go
  pkg/resources/cronjob/cronjob.go
  pkg/resources/deployment/deployment.go
  pkg/resources/deployment/deployment.yaml
  pkg/resources/job/job.go
  pkg/resources/pod/pod.go
  pkg/resources/pod/pod_test.go
Labels: lgtm, approved, size/M
