Repository knative-extensions/reconciler-test, pull requests merged in 2025-08, with the labels that each got.

#807 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/pflag/README.md
  vendor/github.com/spf13/pflag/bool_func.go
  vendor/github.com/spf13/pflag/count.go
  vendor/github.com/spf13/pflag/errors.go
  vendor/github.com/spf13/pflag/flag.go
  vendor/github.com/spf13/pflag/func.go
  vendor/github.com/spf13/pflag/golangflag.go
  vendor/github.com/spf13/pflag/ipnet_slice.go
  vendor/github.com/spf13/pflag/text.go
  vendor/github.com/spf13/pflag/time.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/internal/modindex/lookup.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#809 fix: ConfigureObservability does not panic
  pkg/eventshub/utils.go
  vendor/knative.dev/pkg/observability/resource/default.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#816 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, skip-review
