Repository knative-extensions/reconciler-test, pull requests merged in 2025-07, with the labels that each got.

#799 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#804 retry failed deletions in DeleteResources
  pkg/feature/feature.go
Labels: lgtm, approved, kind/cleanup, size/M

#805 retry update conflicts in manifest Apply
  pkg/manifest/manifest.go
Labels: size/XS, lgtm, approved
